# Run unit tests on any branch/fork pull request
on:
  push:
    branches:
      - master
      - 'dev/**'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

name: Windows unit test

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    # https://www.cybertec-postgresql.com/en/postgresql-github-actions-continuous-integration/
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: conda-env
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |

        eval "$(conda shell.bash hook)"
        conda activate conda-env

        # Test vanilla installation, make sure core modules are importable
        pip install .
        python -c 'import ploomber'
        python -c 'import ploomber.tasks'
        python -c 'import ploomber.products'
        python -c 'import ploomber.clients'

        # install dev requirements
        pip install .[dev]


        # install sample package for tests
        pip install --editable tests/assets/test_pkg

    - name: Run tests
      env:
        PLOOMBER_STATS_ENABLED: false
        PLOOMBER_CLOUD_KEY: ${{ secrets.PLOOMBER_CLOUD_KEY }}
      shell: bash -l {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate conda-env
        pip install pytest-timeout
        pytest tests/sources/test_python_interact.py::test_signature_line_break -vv -rx --ignore=tests/cli/test_cloud_execution.py --ignore=tests/cli/test_cloud.py --ignore=tests/cloud --ignore=tests/telemetry --timeout=120
